### ISSUE TITLE
If we expose the SSL port, why does nntp use_ssl fail?

### ISSUE THREAD

**Issue by cclauss** [greenbender/inn-docker#5]
The pynntp `test_nntp_client_with_ssl()` pytest still xfails.

* greenbender/pynntp#30
* https://github.com/greenbender/pynntp/blob/15815ec71080f05c0baf49575e27742c8d2f4123/tests/integration/inn2/test_inn2.py#L67

**Comment by greenbender** [comment]
inn does not have ssl enabled by default - this can be fixed.

Though since it wll be using a self signed cert we have have to add an env var to `pynntp` to support disabling cert validation, or `pynntp` could supply a key/cert to `inn` via a bind mount and add the cert to the host cert store. There are options.

**Comment by greenbender** [comment]
Resolved in #9

**Comment by greenbender** [comment]
Release https://github.com/greenbender/inn-docker/releases/tag/0.9.1 will support TLS.
